.TH "driver/src/flash.c" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver/src/flash.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <driver/flash\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBstore_data_to_flash\fP (int8_t *data, uint8_t size, uint8_t pos)"
.br
.ti -1c
.RI "uint8_t \fBread_flash\fP (int8_t *data, uint8_t size, uint8_t pos)"
.br
.ti -1c
.RI "void \fBerase_flash\fP (uint8_t *Flash_ptr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void erase_flash (uint8_t * Flash_ptr)"

.SS "uint8_t read_flash (int8_t * data, uint8_t size, uint8_t pos)"

.SS "uint8_t store_data_to_flash (int8_t * data, uint8_t size, uint8_t pos)"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
