.TH "fm_gpio_ctl_arg1" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fm_gpio_ctl_arg1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBbyte\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fB__pad0__\fP:4"
.br
.ti -1c
.RI "   uint8_t \fBGPO3OEN\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBGPO2OEN\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBGPO1OEN\fP:1"
.br
.ti -1c
.RI "   uint8_t \fB__pad1__\fP:1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint8_t fm_gpio_ctl_arg1::__pad0__"

.SS "uint8_t fm_gpio_ctl_arg1::__pad1__"

.SS "uint8_t fm_gpio_ctl_arg1::byte"

.SS "uint8_t fm_gpio_ctl_arg1::GPO1OEN"

.SS "uint8_t fm_gpio_ctl_arg1::GPO2OEN"

.SS "uint8_t fm_gpio_ctl_arg1::GPO3OEN"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
