.TH "fm_rds_status_resp1" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fm_rds_status_resp1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBbyte\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fB__pad0__\fP:2"
.br
.ti -1c
.RI "   uint8_t \fBRDSNEWBLOCKB\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBRDSNEWBLOCKA\fP:1"
.br
.ti -1c
.RI "   uint8_t \fB__pad1__\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBRDSSYNCFOUND\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBRDSSYNCLOST\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBRDSRECV\fP:1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint8_t fm_rds_status_resp1::__pad0__"

.SS "uint8_t fm_rds_status_resp1::__pad1__"

.SS "uint8_t fm_rds_status_resp1::byte"

.SS "uint8_t fm_rds_status_resp1::RDSNEWBLOCKA"

.SS "uint8_t fm_rds_status_resp1::RDSNEWBLOCKB"

.SS "uint8_t fm_rds_status_resp1::RDSRECV"

.SS "uint8_t fm_rds_status_resp1::RDSSYNCFOUND"

.SS "uint8_t fm_rds_status_resp1::RDSSYNCLOST"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
