.TH "fm_rds_status_resp12" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fm_rds_status_resp12 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBbyte\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBBLEA\fP:2"
.br
.ti -1c
.RI "   uint8_t \fBBLEB\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBBLEC\fP:2"
.br
.ti -1c
.RI "   uint8_t \fBBLED\fP:2"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint8_t fm_rds_status_resp12::BLEA"

.SS "uint8_t fm_rds_status_resp12::BLEB"

.SS "uint8_t fm_rds_status_resp12::BLEC"

.SS "uint8_t fm_rds_status_resp12::BLED"

.SS "uint8_t fm_rds_status_resp12::byte"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
