.TH "menu/lang/language.h" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu/lang/language.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGER\fP   1"
.br
.ti -1c
.RI "#define \fBEN\fP   2"
.br
.ti -1c
.RI "#define \fBRADIO_LANGAUGE\fP   \fBGER\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBview_text\fP []"
.br
.ti -1c
.RI "const char \fBradio_text\fP []"
.br
.ti -1c
.RI "const char \fBtatp_text\fP []"
.br
.ti -1c
.RI "const char \fBvolume_text\fP []"
.br
.ti -1c
.RI "const char \fBfreq_text\fP []"
.br
.ti -1c
.RI "const char \fBtext_text\fP []"
.br
.ti -1c
.RI "const char \fBrds_text\fP []"
.br
.ti -1c
.RI "const char \fBptypi_text\fP []"
.br
.ti -1c
.RI "const char \fBrsq_text\fP []"
.br
.ti -1c
.RI "const char \fBcontrast_text\fP []"
.br
.ti -1c
.RI "const char \fBbrightness_text\fP []"
.br
.ti -1c
.RI "const char \fBfixed_text\fP []"
.br
.ti -1c
.RI "const char \fBauto_text\fP []"
.br
.ti -1c
.RI "const char \fBaudio_text\fP []"
.br
.ti -1c
.RI "const char \fBpop_text\fP []"
.br
.ti -1c
.RI "const char \fBclassic_text\fP []"
.br
.ti -1c
.RI "const char \fBjazz_text\fP []"
.br
.ti -1c
.RI "const char \fBhiphop_text\fP []"
.br
.ti -1c
.RI "const char \fBrock_text\fP []"
.br
.ti -1c
.RI "const char \fBnews_text\fP []"
.br
.ti -1c
.RI "const char \fBsource_text\fP []"
.br
.ti -1c
.RI "const char \fBfm_text\fP []"
.br
.ti -1c
.RI "const char \fBam_text\fP []"
.br
.ti -1c
.RI "const char \fBlinein_text\fP []"
.br
.ti -1c
.RI "const char \fBreturn_text\fP []"
.br
.ti -1c
.RI "const char \fBseeking_text\fP []"
.br
.ti -1c
.RI "const char \fBreset_text\fP []"
.br
.ti -1c
.RI "const char \fByes_text\fP []"
.br
.ti -1c
.RI "const char \fBno_text\fP []"
.br
.ti -1c
.RI "const char \fBon_text\fP []"
.br
.ti -1c
.RI "const char \fBoff_text\fP []"
.br
.ti -1c
.RI "const char \fBmain_text\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EN   2"

.SS "#define GER   1"

.SS "#define RADIO_LANGAUGE   \fBGER\fP"

.SH "Variable Documentation"
.PP 
.SS "const char am_text[]"

.SS "const char audio_text[]"

.SS "const char auto_text[]"

.SS "const char brightness_text[]"

.SS "const char classic_text[]"

.SS "const char contrast_text[]"

.SS "const char fixed_text[]"

.SS "const char fm_text[]"

.SS "const char freq_text[]"

.SS "const char hiphop_text[]"

.SS "const char jazz_text[]"

.SS "const char linein_text[]"

.SS "const char main_text[]"

.SS "const char news_text[]"

.SS "const char no_text[]"

.SS "const char off_text[]"

.SS "const char on_text[]"

.SS "const char pop_text[]"

.SS "const char ptypi_text[]"

.SS "const char radio_text[]"

.SS "const char rds_text[]"

.SS "const char reset_text[]"

.SS "const char return_text[]"

.SS "const char rock_text[]"

.SS "const char rsq_text[]"

.SS "const char seeking_text[]"

.SS "const char source_text[]"

.SS "const char tatp_text[]"

.SS "const char text_text[]"

.SS "const char view_text[]"

.SS "const char volume_text[]"

.SS "const char yes_text[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
