.TH "menu/lang/ger/language.c" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu/lang/ger/language.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <menu/lang/language\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBview_text\fP [] = 'Anzeige'"
.br
.ti -1c
.RI "const char \fBradio_text\fP [] = 'Radio'"
.br
.ti -1c
.RI "const char \fBtatp_text\fP [] = 'TA/TP'"
.br
.ti -1c
.RI "const char \fBvolume_text\fP [] = 'Lautstärke'"
.br
.ti -1c
.RI "const char \fBfreq_text\fP [] = 'Frequenz'"
.br
.ti -1c
.RI "const char \fBtext_text\fP [] = 'Anzeige Style'"
.br
.ti -1c
.RI "const char \fBrds_text\fP [] = 'Radio Text'"
.br
.ti -1c
.RI "const char \fBptypi_text\fP [] = 'PTY/\fBPI\fP'"
.br
.ti -1c
.RI "const char \fBrsq_text\fP [] = 'Radio Qualität'"
.br
.ti -1c
.RI "const char \fBcontrast_text\fP [] = 'Kontrast'"
.br
.ti -1c
.RI "const char \fBbrightness_text\fP [] = 'Helligkeit'"
.br
.ti -1c
.RI "const char \fBfixed_text\fP [] = 'Manuel'"
.br
.ti -1c
.RI "const char \fBauto_text\fP [] = 'Auto'"
.br
.ti -1c
.RI "const char \fBaudio_text\fP [] = 'Equlizer'"
.br
.ti -1c
.RI "const char \fBpop_text\fP [] = 'Pop'"
.br
.ti -1c
.RI "const char \fBclassic_text\fP [] = 'Klassik'"
.br
.ti -1c
.RI "const char \fBjazz_text\fP [] = 'Jazz'"
.br
.ti -1c
.RI "const char \fBhiphop_text\fP [] = 'Hip-Hop'"
.br
.ti -1c
.RI "const char \fBrock_text\fP [] = 'Rock'"
.br
.ti -1c
.RI "const char \fBnews_text\fP [] = 'News/Voice'"
.br
.ti -1c
.RI "const char \fBsource_text\fP [] = 'Quelle'"
.br
.ti -1c
.RI "const char \fBfm_text\fP [] = 'FM Audio'"
.br
.ti -1c
.RI "const char \fBam_text\fP [] = 'AM Audio'"
.br
.ti -1c
.RI "const char \fBlinein_text\fP [] = 'Line-In'"
.br
.ti -1c
.RI "const char \fBreturn_text\fP [] = 'Zurück'"
.br
.ti -1c
.RI "const char \fBseeking_text\fP [] = 'Suchlauf'"
.br
.ti -1c
.RI "const char \fBreset_text\fP [] = 'Werkszustand'"
.br
.ti -1c
.RI "const char \fByes_text\fP [] = 'Ja'"
.br
.ti -1c
.RI "const char \fBno_text\fP [] = 'Nein'"
.br
.ti -1c
.RI "const char \fBon_text\fP [] = 'An'"
.br
.ti -1c
.RI "const char \fBoff_text\fP [] = 'Aus'"
.br
.ti -1c
.RI "const char \fBmain_text\fP [] = 'Einstellungen'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char am_text[] = 'AM Audio'"

.SS "const char audio_text[] = 'Equlizer'"

.SS "const char auto_text[] = 'Auto'"

.SS "const char brightness_text[] = 'Helligkeit'"

.SS "const char classic_text[] = 'Klassik'"

.SS "const char contrast_text[] = 'Kontrast'"

.SS "const char fixed_text[] = 'Manuel'"

.SS "const char fm_text[] = 'FM Audio'"

.SS "const char freq_text[] = 'Frequenz'"

.SS "const char hiphop_text[] = 'Hip-Hop'"

.SS "const char jazz_text[] = 'Jazz'"

.SS "const char linein_text[] = 'Line-In'"

.SS "const char main_text[] = 'Einstellungen'"

.SS "const char news_text[] = 'News/Voice'"

.SS "const char no_text[] = 'Nein'"

.SS "const char off_text[] = 'Aus'"

.SS "const char on_text[] = 'An'"

.SS "const char pop_text[] = 'Pop'"

.SS "const char ptypi_text[] = 'PTY/\fBPI\fP'"

.SS "const char radio_text[] = 'Radio'"

.SS "const char rds_text[] = 'Radio Text'"

.SS "const char reset_text[] = 'Werkszustand'"

.SS "const char return_text[] = 'Zurück'"

.SS "const char rock_text[] = 'Rock'"

.SS "const char rsq_text[] = 'Radio Qualität'"

.SS "const char seeking_text[] = 'Suchlauf'"

.SS "const char source_text[] = 'Quelle'"

.SS "const char tatp_text[] = 'TA/TP'"

.SS "const char text_text[] = 'Anzeige Style'"

.SS "const char view_text[] = 'Anzeige'"

.SS "const char volume_text[] = 'Lautstärke'"

.SS "const char yes_text[] = 'Ja'"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
