.TH "driver/src/lcd.c" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver/src/lcd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <driver/lcd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int8_t \fBlcd_replace_special_letter\fP (int8_t chr)"
.br
.ti -1c
.RI "uint8_t \fBlcd_init\fP (uint8_t contrast)"
.br
.ti -1c
.RI "uint8_t \fBlcd_contrast\fP (uint8_t contrast)"
.br
.ti -1c
.RI "uint8_t \fBlcd_write_char\fP (uint8_t symbol)"
.br
.ti -1c
.RI "uint8_t \fBlcd_write_string\fP (const int8_t *str, unsigned char n_bytes)"
.br
.ti -1c
.RI "uint8_t \fBlcd_command\fP (uint8_t command)"
.br
.ti -1c
.RI "uint8_t \fBlcd_set_courser\fP (uint8_t x, uint8_t y)"
.br
.ti -1c
.RI "uint8_t \fBlcd_generatechar\fP (uint8_t code, const uint8_t *data)"
.br
.ti -1c
.RI "uint8_t \fBlcd_generatebargraph\fP ()"
.br
.ti -1c
.RI "uint8_t \fBlcd_create_view\fP (const char *str, uint8_t x, uint8_t y, uint8_t flush)"
.br
.ti -1c
.RI "uint8_t \fBlcd_bargraph\fP (uint8_t \fBvalue\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint8_t lcd_bargraph (uint8_t value)"

.SS "uint8_t lcd_command (uint8_t command)"

.SS "uint8_t lcd_contrast (uint8_t contrast)"

.SS "uint8_t lcd_create_view (const char * str, uint8_t x, uint8_t y, uint8_t flush)"

.SS "uint8_t lcd_generatebargraph ()"

.SS "uint8_t lcd_generatechar (uint8_t code, const uint8_t * data)"

.SS "uint8_t lcd_init (uint8_t contrast)"

.SS "int8_t lcd_replace_special_letter (int8_t chr)"

.SS "uint8_t lcd_set_courser (uint8_t x, uint8_t y)"

.SS "uint8_t lcd_write_char (uint8_t symbol)"

.SS "uint8_t lcd_write_string (const int8_t * str, unsigned char n_bytes)"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
