.TH "libs/log_exp_table.h" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libs/log_exp_table.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBexp_table\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t exp_table[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
