.TH "menu/menu_struct.h" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu/menu_struct.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'menu\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmenu_entry\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef const struct \fBmenu_entry\fP \fBMENU_ENTRY\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBmain_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBview_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBradio_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBfreq_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBvolume_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBsource_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBam_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBfm_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBlinein_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBtext_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBrds_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBrsq_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBptypi_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBtatp_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBtatp_on_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBtatp_off_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBtatp_return_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBfreq_seeking_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBfreq_fixed_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBfreq_return_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBradio_return_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBcontrast_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBbrightness_return_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBtext_return_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBbrightness_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBbrightness_fixed_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBbrightness_auto_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBaudio_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBrock_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBhiphop_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBpop_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBjazz_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBclassic_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBnews_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBaudio_return_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBsource_return_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBreset_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBreset_no_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBreset_yes_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBview_return_entry\fP"
.br
.ti -1c
.RI "\fBMENU_ENTRY\fP \fBmain_return_entry\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef const struct \fBmenu_entry\fP  \fBMENU_ENTRY\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBMENU_ENTRY\fP am_entry"

.SS "\fBMENU_ENTRY\fP audio_entry"

.SS "\fBMENU_ENTRY\fP audio_return_entry"

.SS "\fBMENU_ENTRY\fP brightness_auto_entry"

.SS "\fBMENU_ENTRY\fP brightness_entry"

.SS "\fBMENU_ENTRY\fP brightness_fixed_entry"

.SS "\fBMENU_ENTRY\fP brightness_return_entry"

.SS "\fBMENU_ENTRY\fP classic_entry"

.SS "\fBMENU_ENTRY\fP contrast_entry"

.SS "\fBMENU_ENTRY\fP fm_entry"

.SS "\fBMENU_ENTRY\fP freq_entry"

.SS "\fBMENU_ENTRY\fP freq_fixed_entry"

.SS "\fBMENU_ENTRY\fP freq_return_entry"

.SS "\fBMENU_ENTRY\fP freq_seeking_entry"

.SS "\fBMENU_ENTRY\fP hiphop_entry"

.SS "\fBMENU_ENTRY\fP jazz_entry"

.SS "\fBMENU_ENTRY\fP linein_entry"

.SS "\fBMENU_ENTRY\fP main_entry"

.SS "\fBMENU_ENTRY\fP main_return_entry"

.SS "\fBMENU_ENTRY\fP news_entry"

.SS "\fBMENU_ENTRY\fP pop_entry"

.SS "\fBMENU_ENTRY\fP ptypi_entry"

.SS "\fBMENU_ENTRY\fP radio_entry"

.SS "\fBMENU_ENTRY\fP radio_return_entry"

.SS "\fBMENU_ENTRY\fP rds_entry"

.SS "\fBMENU_ENTRY\fP reset_entry"

.SS "\fBMENU_ENTRY\fP reset_no_entry"

.SS "\fBMENU_ENTRY\fP reset_yes_entry"

.SS "\fBMENU_ENTRY\fP rock_entry"

.SS "\fBMENU_ENTRY\fP rsq_entry"

.SS "\fBMENU_ENTRY\fP source_entry"

.SS "\fBMENU_ENTRY\fP source_return_entry"

.SS "\fBMENU_ENTRY\fP tatp_entry"

.SS "\fBMENU_ENTRY\fP tatp_off_entry"

.SS "\fBMENU_ENTRY\fP tatp_on_entry"

.SS "\fBMENU_ENTRY\fP tatp_return_entry"

.SS "\fBMENU_ENTRY\fP text_entry"

.SS "\fBMENU_ENTRY\fP text_return_entry"

.SS "\fBMENU_ENTRY\fP view_entry"

.SS "\fBMENU_ENTRY\fP view_return_entry"

.SS "\fBMENU_ENTRY\fP volume_entry"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
