.TH "settings/msp430_pin_mapping.h" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
settings/msp430_pin_mapping.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMSP_RXD\fP   1\&.1"
.br
.ti -1c
.RI "#define \fBMSP_TXD\fP   1\&.2"
.br
.ti -1c
.RI "#define \fBEN1_A\fP   1\&.3"
.br
.ti -1c
.RI "#define \fBEN1_B\fP   1\&.4"
.br
.ti -1c
.RI "#define \fBEN1_TAST\fP   1\&.5"
.br
.ti -1c
.RI "#define \fBSI_RST\fP   3\&.1"
.br
.ti -1c
.RI "#define \fBSI_INT\fP   2\&.3"
.br
.ti -1c
.RI "#define \fBSI_EN\fP   3\&.0"
.br
.ti -1c
.RI "#define \fBEN2_A\fP   2\&.0"
.br
.ti -1c
.RI "#define \fBEN2_B\fP   2\&.1"
.br
.ti -1c
.RI "#define \fBEN2_TAST\fP   2\&.2"
.br
.ti -1c
.RI "#define \fBAUIDO_SW_GND\fP   3\&.2"
.br
.ti -1c
.RI "#define \fBAUDIO_SW_LINE\fP   3\&.3"
.br
.ti -1c
.RI "#define \fBPCA_ON_OFF\fP   2\&.4"
.br
.ti -1c
.RI "#define \fBPCA_INT\fP   2\&.5"
.br
.ti -1c
.RI "#define \fBANT_MF\fP   3\&.5"
.br
.ti -1c
.RI "#define \fBANT_LF\fP   3\&.6"
.br
.ti -1c
.RI "#define \fBAMP_SHUTDOWN\fP   3\&.7"
.br
.ti -1c
.RI "#define \fBSCL\fP   1\&.6"
.br
.ti -1c
.RI "#define \fBSDA\fP   1\&.7"
.br
.ti -1c
.RI "#define \fBPWM_RST\fP   1\&.0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AMP_SHUTDOWN   3\&.7"

.SS "#define ANT_LF   3\&.6"

.SS "#define ANT_MF   3\&.5"

.SS "#define AUDIO_SW_LINE   3\&.3"

.SS "#define AUIDO_SW_GND   3\&.2"

.SS "#define EN1_A   1\&.3"

.SS "#define EN1_B   1\&.4"

.SS "#define EN1_TAST   1\&.5"

.SS "#define EN2_A   2\&.0"

.SS "#define EN2_B   2\&.1"

.SS "#define EN2_TAST   2\&.2"

.SS "#define MSP_RXD   1\&.1"

.SS "#define MSP_TXD   1\&.2"

.SS "#define PCA_INT   2\&.5"

.SS "#define PCA_ON_OFF   2\&.4"

.SS "#define PWM_RST   1\&.0"

.SS "#define SCL   1\&.6"

.SS "#define SDA   1\&.7"

.SS "#define SI_EN   3\&.0"

.SS "#define SI_INT   2\&.3"

.SS "#define SI_RST   3\&.1"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
