.TH "pca9530_ctl" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pca9530_ctl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pca9530\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fB__pad0__\fP: 3"
.br
.ti -1c
.RI "uint8_t \fBAI\fP: 1"
.br
.ti -1c
.RI "uint8_t \fB__pad1__\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBADDRESS\fP: 3"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t pca9530_ctl::__pad0__"

.SS "uint8_t pca9530_ctl::__pad1__"

.SS "uint8_t pca9530_ctl::ADDRESS"

.SS "uint8_t pca9530_ctl::AI"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
