.TH "power_up_arg1" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
power_up_arg1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBbyte\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBCTSIEN\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBGPO2OEN\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBPATCH\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBXOSCEN\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBFUNC\fP:4"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint8_t power_up_arg1::byte"

.SS "uint8_t power_up_arg1::CTSIEN"

.SS "uint8_t power_up_arg1::FUNC"

.SS "uint8_t power_up_arg1::GPO2OEN"

.SS "uint8_t power_up_arg1::PATCH"

.SS "uint8_t power_up_arg1::XOSCEN"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
