.TH "radio_stats" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radio_stats \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBbyte\fP"
.br
.ti -1c
.RI "uint16_t \fBrds_station_valid\fP:1"
.br
.ti -1c
.RI "uint16_t \fBrds_text_valid\fP:1"
.br
.ti -1c
.RI "uint16_t \fBrds_time_valid\fP:1"
.br
.ti -1c
.RI "uint16_t \fBrds_pty_valid\fP:1"
.br
.ti -1c
.RI "uint16_t \fBfreq_valid\fP:1"
.br
.ti -1c
.RI "uint16_t \fB__pad0__\fP:11"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint16_t radio_stats::__pad0__"

.SS "uint16_t radio_stats::byte"

.SS "uint16_t radio_stats::freq_valid"

.SS "uint16_t radio_stats::rds_pty_valid"

.SS "uint16_t radio_stats::rds_station_valid"

.SS "uint16_t radio_stats::rds_text_valid"

.SS "uint16_t radio_stats::rds_time_valid"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
