.TH "status" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBSTCINT\fP:1"
.br
.ti -1c
.RI "uint8_t \fB__pad0__\fP:1"
.br
.ti -1c
.RI "uint8_t \fBRDSINT\fP:1"
.br
.ti -1c
.RI "uint8_t \fBRSQINT\fP:1"
.br
.ti -1c
.RI "uint8_t \fB__pad1__\fP:2"
.br
.ti -1c
.RI "uint8_t \fBERR\fP:1"
.br
.ti -1c
.RI "uint8_t \fBCTS\fP:1"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t status::__pad0__"

.SS "uint8_t status::__pad1__"

.SS "uint8_t status::CTS"

.SS "uint8_t status::ERR"

.SS "uint8_t status::RDSINT"

.SS "uint8_t status::RSQINT"

.SS "uint8_t status::STCINT"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
