.TH "Timer.h" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <driver/encoder\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbasic_clock_init\fP (void)"
.br
.ti -1c
.RI "void \fBTimer_A_init\fP (void)"
.br
.ti -1c
.RI "void \fB_delay_ms\fP (int ms)"
.br
.ti -1c
.RI "void \fB_delay_us\fP (int us)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _delay_ms (int ms)"

.SS "void _delay_us (int us)"

.SS "void basic_clock_init (void)"

.SS "void Timer_A_init (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
