.TH "block_b" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
block_b \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fB__pad0__\fP:5"
.br
.ti -1c
.RI "uint16_t \fBPTY\fP:5"
.br
.ti -1c
.RI "uint16_t \fBTP\fP:1"
.br
.ti -1c
.RI "uint16_t \fBGROUP_CHAR\fP:1"
.br
.ti -1c
.RI "uint16_t \fBGROUP_NUM\fP:4"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint16_t block_b::__pad0__"

.SS "uint16_t block_b::GROUP_CHAR"

.SS "uint16_t block_b::GROUP_NUM"

.SS "uint16_t block_b::PTY"

.SS "uint16_t block_b::TP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
