.TH "err" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
err \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBBLED\fP:2"
.br
.ti -1c
.RI "uint8_t \fBBLEC\fP:2"
.br
.ti -1c
.RI "uint8_t \fBBLEB\fP:2"
.br
.ti -1c
.RI "uint8_t \fBBLEA\fP:2"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t err::BLEA"

.SS "uint8_t err::BLEB"

.SS "uint8_t err::BLEC"

.SS "uint8_t err::BLED"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
