.TH "fifo" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fifo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBRDSFIFOUSED\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t fifo::RDSFIFOUSED"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
