.TH "fm_hicut_cutoff_freq" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fm_hicut_cutoff_freq \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBbyte\fP"
.br
.ti -1c
.RI "uint8_t \fBbytes\fP [2]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fB__pad0__\fP:9"
.br
.ti -1c
.RI "   uint16_t \fBMAX_AUDIO_FREQ\fP:3"
.br
.ti -1c
.RI "   uint16_t \fB__pad1__\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBFREQUENCY\fP:3"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint16_t fm_hicut_cutoff_freq::__pad0__"

.SS "uint16_t fm_hicut_cutoff_freq::__pad1__"

.SS "uint16_t fm_hicut_cutoff_freq::byte"

.SS "uint8_t fm_hicut_cutoff_freq::bytes[2]"

.SS "uint16_t fm_hicut_cutoff_freq::FREQUENCY"

.SS "uint16_t fm_hicut_cutoff_freq::MAX_AUDIO_FREQ"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
