.TH "fm_seek_tune_snr_thres" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fm_seek_tune_snr_thres \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBbyte\fP"
.br
.ti -1c
.RI "uint8_t \fBbytes\fP [2]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fB__pad0__\fP:9"
.br
.RI "\fIReserved\&. \fP"
.ti -1c
.RI "   uint16_t \fBSKSNR\fP:7"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint16_t fm_seek_tune_snr_thres::__pad0__"

.PP
Reserved\&. 
.SS "uint16_t fm_seek_tune_snr_thres::byte"

.SS "uint8_t fm_seek_tune_snr_thres::bytes[2]"

.SS "uint16_t fm_seek_tune_snr_thres::SKSNR"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
