.TH "fm_soft_mute_atk_rate" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fm_soft_mute_atk_rate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBbyte\fP"
.br
.ti -1c
.RI "uint8_t \fBbytes\fP [2]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fB__pad0__\fP:1"
.br
.RI "\fIReserved\&. \fP"
.ti -1c
.RI "   uint16_t \fBATTACK\fP:15"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint16_t fm_soft_mute_atk_rate::__pad0__"

.PP
Reserved\&. 
.SS "uint16_t fm_soft_mute_atk_rate::ATTACK"

.SS "uint16_t fm_soft_mute_atk_rate::byte"

.SS "uint8_t fm_soft_mute_atk_rate::bytes[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
