.TH "fm_tune_status_resp1" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fm_tune_status_resp1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBbyte\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fB__pad0__\fP:6"
.br
.ti -1c
.RI "   uint8_t \fBAFCRL\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBVALID\fP:1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint8_t fm_tune_status_resp1::__pad0__"

.SS "uint8_t fm_tune_status_resp1::AFCRL"

.SS "uint8_t fm_tune_status_resp1::byte"

.SS "uint8_t fm_tune_status_resp1::VALID"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
