.TH "group_0b" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group_0b \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBPI_CODE\fP"
.br
.ti -1c
.RI "uint16_t \fBCI\fP: 2"
.br
.ti -1c
.RI "uint16_t \fBDI\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBMS\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBTA\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBPTY\fP: 5"
.br
.ti -1c
.RI "uint16_t \fBTP\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBGROUP_CHAR\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBGROUP_NUM\fP: 4"
.br
.ti -1c
.RI "uint8_t \fBAF\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPS_NAME\fP [2]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t group_0b::AF[2]"

.SS "uint16_t group_0b::CI"

.SS "uint16_t group_0b::DI"

.SS "uint16_t group_0b::GROUP_CHAR"

.SS "uint16_t group_0b::GROUP_NUM"

.SS "uint16_t group_0b::MS"

.SS "uint16_t group_0b::PI_CODE"

.SS "uint8_t group_0b::PS_NAME[2]"

.SS "uint16_t group_0b::PTY"

.SS "uint16_t group_0b::TA"

.SS "uint16_t group_0b::TP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
