.TH "group_2b" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group_2b \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBPI_CODE\fP"
.br
.ti -1c
.RI "uint16_t \fBB\fP: 4"
.br
.ti -1c
.RI "uint16_t \fBA_B\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBPTY\fP: 5"
.br
.ti -1c
.RI "uint16_t \fBTP\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBGROUP_CHAR\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBGROUP_NUM\fP: 4"
.br
.ti -1c
.RI "uint16_t \fBPI_CODE_2\fP"
.br
.ti -1c
.RI "uint8_t \fBSEGMENT\fP [2]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint16_t group_2b::A_B"

.SS "uint16_t group_2b::B"

.SS "uint16_t group_2b::GROUP_CHAR"

.SS "uint16_t group_2b::GROUP_NUM"

.SS "uint16_t group_2b::PI_CODE"

.SS "uint16_t group_2b::PI_CODE_2"

.SS "uint16_t group_2b::PTY"

.SS "uint8_t group_2b::SEGMENT[2]"

.SS "uint16_t group_2b::TP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
