.TH "group_4a" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group_4a \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBPI_CODE\fP:16"
.br
.ti -1c
.RI "uint16_t \fBDATE_H\fP:2"
.br
.ti -1c
.RI "uint16_t \fB__pad0__\fP:3"
.br
.ti -1c
.RI "uint16_t \fBPTY\fP: 5"
.br
.ti -1c
.RI "uint16_t \fBTP\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBGROUP_CHAR\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBGROUP_NUM\fP: 4"
.br
.ti -1c
.RI "uint16_t \fBHOUR_H\fP:1"
.br
.ti -1c
.RI "uint16_t \fBDATE_L\fP:15"
.br
.ti -1c
.RI "int16_t \fBTIME_OFF\fP:6"
.br
.ti -1c
.RI "uint16_t \fBMINUTE\fP:6"
.br
.ti -1c
.RI "uint16_t \fBHOUR_L\fP:4"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint16_t group_4a::__pad0__"

.SS "uint16_t group_4a::DATE_H"

.SS "uint16_t group_4a::DATE_L"

.SS "uint16_t group_4a::GROUP_CHAR"

.SS "uint16_t group_4a::GROUP_NUM"

.SS "uint16_t group_4a::HOUR_H"

.SS "uint16_t group_4a::HOUR_L"

.SS "uint16_t group_4a::MINUTE"

.SS "uint16_t group_4a::PI_CODE"

.SS "uint16_t group_4a::PTY"

.SS "int16_t group_4a::TIME_OFF"

.SS "uint16_t group_4a::TP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
