.TH "info" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBRDSRECV\fP:1"
.br
.ti -1c
.RI "uint8_t \fBRDSSYNCLOST\fP:1"
.br
.ti -1c
.RI "uint8_t \fBRDSSYNCFOUND\fP:1"
.br
.ti -1c
.RI "uint8_t \fB__pad0__\fP:1"
.br
.ti -1c
.RI "uint8_t \fBRDSNEWBLOCKA\fP:1"
.br
.ti -1c
.RI "uint8_t \fBRDSNEWBLOCKB\fP:1"
.br
.ti -1c
.RI "uint8_t \fB__pad1__\fP:2"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t info::__pad0__"

.SS "uint8_t info::__pad1__"

.SS "uint8_t info::RDSNEWBLOCKA"

.SS "uint8_t info::RDSNEWBLOCKB"

.SS "uint8_t info::RDSRECV"

.SS "uint8_t info::RDSSYNCFOUND"

.SS "uint8_t info::RDSSYNCLOST"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
