.TH "libs/log_exp_table.c" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libs/log_exp_table.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <libs/log_exp_table\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBexp_table\fP [100]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t exp_table[100]"
\fBInitial value:\fP
.PP
.nf
= {
        1 ,1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
        3, 3, 3, 4, 4, 4, 4, 5, 5, 5,
        5, 6, 6, 6, 7, 7, 8, 8, 8, 9,
        9, 10, 10, 11, 12, 12, 13, 14, 15, 16,
        16, 17, 18, 19, 21, 22, 23, 24, 26, 27,
        29, 30, 32, 34, 36, 38, 40, 43, 45, 48,
        50, 53, 56, 60, 63, 67, 70, 74, 79, 83,
        88, 93, 98, 104, 110, 116, 123, 130, 138, 146,
        154, 163, 172, 182, 193, 204, 216, 228, 241, 255
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
