.TH "driver/src/pca9534.c" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver/src/pca9534.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <driver/pca9534\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBpca9534_output\fP (uint8_t byte)"
.br
.ti -1c
.RI "uint8_t \fBpca9534_config\fP (uint8_t config)"
.br
.ti -1c
.RI "uint8_t \fBpca9534_input\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint8_t pca9534_config (uint8_t config)"

.SS "uint8_t pca9534_input ()"

.SS "uint8_t pca9534_output (uint8_t byte)"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
