.TH "pca9530" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pca9530 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pca9530\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBfreq0\fP"
.br
.ti -1c
.RI "uint8_t \fBpwm0\fP"
.br
.ti -1c
.RI "uint8_t \fBfreq1\fP"
.br
.ti -1c
.RI "uint8_t \fBpwm1\fP"
.br
.ti -1c
.RI "enum \fBPCA9530_LED_STATE\fP \fBled0\fP"
.br
.ti -1c
.RI "enum \fBPCA9530_LED_STATE\fP \fBled1\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t pca9530::freq0"

.SS "uint8_t pca9530::freq1"

.SS "enum \fBPCA9530_LED_STATE\fP pca9530::led0"

.SS "enum \fBPCA9530_LED_STATE\fP pca9530::led1"

.SS "uint8_t pca9530::pwm0"

.SS "uint8_t pca9530::pwm1"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
