.TH "pi" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pi \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBPROGRAMM_REF_NUM\fP:8"
.br
.ti -1c
.RI "uint16_t \fBAREA_CODE\fP:4"
.br
.ti -1c
.RI "uint16_t \fBCOUNTRY_CODE\fP:4"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint16_t pi::AREA_CODE"

.SS "uint16_t pi::COUNTRY_CODE"

.SS "uint16_t pi::PROGRAMM_REF_NUM"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
