.TH "settings/radio_configuration.h" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
settings/radio_configuration.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <si4735_cmd_prop\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRADIO_VALID_SNR\fP   10"
.br
.ti -1c
.RI "#define \fBRADIO_VALID_RSSI\fP   20"
.br
.ti -1c
.RI "#define \fBRADIO_BOT_FREQ\fP   0x222E"
.br
.ti -1c
.RI "#define \fBRADIO_TOP_FREQ\fP   0x2A30"
.br
.ti -1c
.RI "#define \fBRADIO_SEEK_FREQ_SPACE\fP   \fBSKSPACE_10\fP"
.br
.ti -1c
.RI "#define \fBRADIO_CALBC1\fP   CALBC1_16MHZ"
.br
.ti -1c
.RI "#define \fBRADIO_CALDCO\fP   CALDCO_16MHZ"
.br
.ti -1c
.RI "#define \fBRADIO_DCO_FREQ\fP   16"
.br
.ti -1c
.RI "#define \fBRADIO_LCD_REFRESCH\fP   500"
.br
.ti -1c
.RI "#define \fBRADIO_ENCODER_POLL\fP   100"
.br
.ti -1c
.RI "#define \fBRADIO_MCLK\fP   16"
.br
.ti -1c
.RI "#define \fBRADIO_SCLK\fP   2"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RADIO_BOT_FREQ   0x222E"

.SS "#define RADIO_CALBC1   CALBC1_16MHZ"

.SS "#define RADIO_CALDCO   CALDCO_16MHZ"

.SS "#define RADIO_DCO_FREQ   16"

.SS "#define RADIO_ENCODER_POLL   100"

.SS "#define RADIO_LCD_REFRESCH   500"

.SS "#define RADIO_MCLK   16"

.SS "#define RADIO_SCLK   2"

.SS "#define RADIO_SEEK_FREQ_SPACE   \fBSKSPACE_10\fP"

.SS "#define RADIO_TOP_FREQ   0x2A30"

.SS "#define RADIO_VALID_RSSI   20"

.SS "#define RADIO_VALID_SNR   10"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
