.TH "rds" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rds \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Radio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBSTATUS\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBINFO\fP \fBinfo\fP"
.br
.ti -1c
.RI "\fBSYNC\fP \fBsync\fP"
.br
.ti -1c
.RI "\fBFIFO\fP \fBfifo\fP"
.br
.ti -1c
.RI "\fBPI\fP \fBpi\fP"
.br
.ti -1c
.RI "\fBBLOCK_B\fP \fBblock_b\fP"
.br
.ti -1c
.RI "uint8_t \fBblock\fP [4]"
.br
.ti -1c
.RI "\fBERR\fP \fBerr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t rds::block[4]"

.SS "\fBBLOCK_B\fP rds::block_b"

.SS "\fBERR\fP rds::err"

.SS "\fBFIFO\fP rds::fifo"

.SS "\fBINFO\fP rds::info"

.SS "\fBPI\fP rds::pi"

.SS "\fBSTATUS\fP rds::status"

.SS "\fBSYNC\fP rds::sync"


.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
