.TH "driver/src/tpa2016d2.c" 3 "Thu Mar 26 2015" "Version V2.0" "FHFM-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver/src/tpa2016d2.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <driver/tpa2016d2\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAmplifier_init\fP (uint8_t Start_Mode, int8_t Start_Gain)"
.br
.ti -1c
.RI "void \fBAmplifier_Shutdown\fP (uint8_t Shutdown)"
.br
.ti -1c
.RI "void \fBAmplifier_Gain\fP (int8_t Gain)"
.br
.ti -1c
.RI "void \fBAmplifier_set_equalizer_mode\fP (uint8_t Mode, int8_t Gain)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Amplifier_Gain (int8_t Gain)"

.SS "void Amplifier_init (uint8_t Start_Mode, int8_t Start_Gain)"

.SS "void Amplifier_set_equalizer_mode (uint8_t Mode, int8_t Gain)"

.SS "void Amplifier_Shutdown (uint8_t Shutdown)"

.SH "Author"
.PP 
Generated automatically by Doxygen for FHFM-Radio from the source code\&.
